---
name: Hello World
description: Greet someone
inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: World
outputs:
  random-number:
    description: Random number
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: composite
  steps:
    - name: Set Greeting
      run: echo "Hello $INPUT_WHO_TO_GREET."
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: To list the file
      run: ls -lrt
      shell: bash
    - name: To check file path
      run: pwd
      shell: bash
    - name: Giving permission to script
      run: chmod +x .github/actions/hello-world-composite-action/goodbye.sh
      shell: bash
    - name: Run goodbye.sh
      run: sh -x .github/actions/hello-world-composite-action/goodbye.sh
      shell: bash
